ReportGenerator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace ReportGenerator.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ReportGenerator/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using ReportGenerator.Models;
using ReportGenerator.ViewModel.Report;


namespace ReportGenerator.Controllers
{
    public class ReportController : Controller
    {
        CS3 context = new CS3();


       
        public static object Definitions { get; private set; }

        // GET: Report
        public ActionResult Index()
        {
            transactionTypesViewModel viewModel = new transactionTypesViewModel();


            //operatorList.Select(p => p.OperatorType).Distinct();
            var transactionTypes = context.stkhstms.Select(tt => tt.transaction_type).Distinct().ToList();

            //viewModel.transactionType = transactionTypes.ToList();
          ViewData["tt"] = transactionTypes;


            return View(ViewData["tt"]);
        }

        public ActionResult ReportList()
        {

            List<string> reportlist = GetAllAvailableReports();

            //List<string> list = from e in XDocument.Load("..\\..\\AllAvailableReports.xml");
            //                    select e;







            ////string xml = "<Ids><id>1</id><id>2</id></Ids>";


            //XmlDocument xmlDoc = new XmlDocument();
            //xmlDoc.Load(@"../App_Data/AllAvailableReports.xml");

            //XmlNodeList nodeList = xmlDoc.DocumentElement.SelectNodes("/Table/Product");

            //XDocument doc = XDocument.Parse(xmlDoc);

            //List<string> list = doc.Root.Elements("id")
            //             .Select(e => e.Value)
            //             .ToList();

            ViewBag.reportlist = reportlist;
            return View();
        }


        public static List<string> GetAllAvailableReports()
        {
            return GetAllAvailableReportsByGroup();
        }


        public static List<string> GetAllAvailableReportsByGroup()
        {
           var reportNamesList = new List<string>();

          //string XMLfile = System.Web.HttpContext.Current.Server.MapPath(Definitions.GetEnumDescription(Definitions.MapPaths.AllAvailableReports));


            string XMLfile = System.Web.HttpContext.Current.Server.MapPath("~/App_Data/AllAvailableReports.xml");
            DataSet ds = new DataSet();
            // Create new FileStream with which to read the schema.
            System.IO.FileStream fsReadXml = new System.IO.FileStream
                (XMLfile, System.IO.FileMode.Open);

            ds.ReadXml(fsReadXml);

            fsReadXml.Close();

            DataView dv = ds.Tables[0].DefaultView;

            DataTable dt = dv.ToTable();


            foreach (DataRow row in dt.Rows)
            {
                reportNamesList.Add(row["ID"].ToString());
            }


            return reportNamesList;
        }
    }
}

ReportGenerator/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ReportGenerator/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ReportGenerator/Views/Home/Index.cshtml
<style>
    .container a {
        width: 200px;
        height: 200px
    }
</style>

<script language="javascript" type="text/javascript">

    // make the menu item active.
    $(document).ready(function () {

        $('ul li a').filter(function () {

            if ($(this).text() === 'Home') {
                $(this).addClass("active");
            };

        });

    });

</script>
<div class="container">
    <div class="row margin_top90">
        <div class="col-lg-4 text_align_center">
            @*@if ((Session["User_View"] != null && (bool)Session["User_View"]) || (Session["accountHolder"] != null && (bool)Session["accountHolder"]))
                {*@
            <a href="@Url.Action("Index", "Report")">
                <figure>
                    <img src="~/Content/img/measurements_blue.png" class="home_menu_items" />
                    <figcaption class="stats_heading margin_top30">MANAGEMENT ACCOUNTS</figcaption>
                </figure>
            </a>@*}*@
        </div>
        <div class="col-lg-4 text_align_center">
            @*@if ((Session["Measurement_View"] != null && (bool)Session["Measurement_View"]) || (Session["accountHolder"] != null && (bool)Session["accountHolder"]))
                {*@
            <a href="@Url.Action("Index", "Measurement")">
                <figure>
                    <img src="~/Content/img/measurements.png" class="home_menu_items" />
                    <figcaption class="stats_heading margin_top30">HUMAN RESOURCES</figcaption>
                </figure>
            </a>@*}*@
        </div>
        <div class="col-lg-4 text_align_center">
            @if ((Session["Device_View"] != null && (bool)Session["Device_View"]) || (Session["accountHolder"] != null && (bool)Session["accountHolder"]))
            {
                <a href="@Url.Action("Index", "Device")">
                    <figure>
                        <img src="~/Content/img/devices_blue.png" class="home_menu_items" />
                        <figcaption class="stats_heading margin_top30">DEVICES</figcaption>
                    </figure>
                </a>
            }
        </div>
    </div>
    <div class="row margin_top90">
        <div class="col-lg-4 text_align_center">
            @if ((Session["User_View"] != null && (bool)Session["User_View"]) || (Session["accountHolder"] != null && (bool)Session["accountHolder"]))
            {
                <a href="@Url.Action("UserPermission", "User")">
                    <figure>
                        <img src="~/Content/img/subaccounts_blue.png" class="home_menu_items" />
                        <figcaption class="stats_heading margin_top30">USERS</figcaption>
                    </figure>
                </a>}
        </div>
        <div class="col-lg-4 text_align_center">
            @if ((Session["Account_View"] != null && (bool)Session["Account_View"]) || (Session["accountHolder"] != null && (bool)Session["accountHolder"]))
            {
                <a href="@Url.Action("AccountList", "Account")">
                    <figure>
                        <img src="~/Content/img/account.png" class="home_menu_items" />
                        <figcaption class="stats_heading margin_top30">SUB COMPANIES</figcaption>
                    </figure>
                </a>}
        </div>
    </div>
</div>